# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: TechnicheLabs.Codayak
PackageVersion: 1.7.0
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Techniche-Labs/codayak-releases/releases/download/v1.7.0/Codayak_Setup_1.7.0.exe
  InstallerSha256: FEC04417DDAA1C5A0E20B2992803D4893E8E0F734718FC62C254A18FA1B680EA
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-09-30
